### ISSUE TITLE
Persistent "fatal: reference is not a tree: <sha>"

### ISSUE THREAD

**Issue by leemhenson** [buildkite/agent#581] opened 2017-11-10 12:10 UTC
We've had this problem for many months now. This morning I upgraded to the `unstable` release (`v3.0-beta.34`) in the hope that it might magically fix it. Alas, it did not.

```
Preparing build directory

# Changing working directory to "/var/lib/buildkite-agent/builds/<some-build-agent-id>/music-glue/graph"
--
  | # Host "github.com" already in list of known hosts at "/var/lib/buildkite-agent/.ssh/known_hosts"
  | $ git remote set-url origin git@github.com:musicglue/some-repo-name.git
  | $ git clean -fxdq
  | $ git submodule foreach --recursive git clean -fxdq
  | # Fetch and checkout pull request head
  | $ git fetch -v origin refs/pull/3520/head
  | From github.com:musicglue/some-repo-name
  | * branch            refs/pull/3520/head -> FETCH_HEAD
  | # FETCH_HEAD is now `2c7e5aaae713c3d11a96944cd91ba8cf6df422f5`
  | $ git checkout -f 7cd2497f55ba2ab88133c21fe4da3a804fe4dd1a
  | fatal: reference is not a tree: 7cd2497f55ba2ab88133c21fe4da3a804fe4dd1a
  | # Skipping artifact upload, no checkout
  | 🚨 Error: Error running `/usr/bin/git checkout -f 7cd2497f55ba2ab88133c21fe4da3a804fe4dd1a`: exit status 128
```

I'm pretty amazed that `FETCH_HEAD` is `2c7e5aaae713c3d11a96944cd91ba8cf6df422f5` as that is a commit from December 2016! The only way to get the build to run is to do `New Build` via the UI and paste the sha of the commit into the popup.

We're seeing this issue across numerous pipelines in our account now. Is there something we can do to resolve it?

Thanks!

**Comment by lox** [comment] 2017-11-18 06:27
Sorry for the slow response on this one @leemhenson, fell off my radar. I don't suppose you are using a branch name that was once a pull request's branch name? This might be an issue with our pull request cache. @sj26 any thoughts?

**Comment by toolmantim** [comment] 2017-11-20 05:30
Buildkite might still think that the branch is an open pull request, so it's trying to do an optimised fetch. This might happen if the pull request closing webhook wasn't received properly by us for some reason (it can happen). We can manually mark the PR as closed, and disassociate the branch the pull request for you. Just let us know… probably best via email: support@buildkite.com

**Comment by toolmantim** [comment] 2017-11-20 05:31
Sorry that it's picking it up incorrect @leemhenson — and thanks for providing all those details!

**Comment by leemhenson** [comment] 2017-11-20 10:22
I have sent an email. Thanks.

**Comment by toolmantim** [comment] 2017-11-23 00:55
All fixed! Sorry about the problem. If this comes up again, shoot an email to support and we'll help you out (and dig into the cause)

**Closed by toolmantim** 2017-11-23 00:55 UTC

**Comment by petemounce** [comment] 2018-10-26 08:59
Ah, we've been having this issue as well; we're hoping it'll be mitigated via #812, and this is the reason (belatedly; didn't see this ticket) that we wanted that PR to get merged.

Reading this, though - seems likely it won't be.

For context - I see this happen correlated to when I have force-pushed a branch, almost always after having rebased from `master`.

**Comment by sj26** [comment] 2018-10-28 23:52
Hi @petemounce! :wave:

That sounds like a different issue indeed. This issue here is about the pull request cache. Your issue sounds like a commit that Buildkite can't fetch from the git remote any more. Force pushes which remove commit history will result in failed builds if that commit is no longer reachable from any ref on the remote, or if it's no longer in the pull request history for a pull request build. The only workaround is to ignore the failed builds (they've become irrelevant!) or avoid force pushing while there are still builds in progress.

**Comment by petemounce** [comment] 2018-10-29 07:16
The thing is that the problem persists, I think, after a subsequent push of a normal commit.

Is this what the skip options are for on a pipeline...?

**Comment by sj26** [comment] 2018-10-29 08:39
@petemounce oh, that might be the cache then, sorry! Could you email us the specifics of a build you've seen failing so we can investigate for you? support@buildkite.com
