### ISSUE TITLE
Sourcing files

### ISSUE THREAD

**Issue by phazel** [buildkite/agent#1505] opened 2021-09-08 07:56 UTC
Hi there. I'm trying to install [nvm](https://github.com/nvm-sh/nvm) on my agent using the [bootstrap script](https://buildkite.com/docs/agent/v3/elastic-ci-aws#customizing-instances-with-a-bootstrap-script) option provided with the Elastic CI stack. I'd even be happy to settle for installing it every time I run a step, but I'm having this issue regardless of which way I try to go about it. In order to install nvm, I need to download and run their install script via `curl` or `wget`, which goes fine. This results in a `.nvm` directory in my home directory and some lines added to the agent's `.bashrc` file. These lines source `nvm` itself and make it available for use.

**Bootstrap script**
```bash
#!/usr/bin/env bash
set -e
su buildkite-agent
# install nvm (node version manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
```

**Lines added to .bashrc by nvm's install.sh**
```bash
export NVM_DIR="$HOME/.nvm"
  | [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  | [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

Which means that in order to actually use `nvm` in my pipeline I have to source my `.bashrc` file beforehand, or at least source `~/.nvm/nvm.sh` directly. Here's where the trouble comes in. Whenever I try to run `source` or `.` on the `nvm.sh` file in the Buildkite agent either directly or through the `.bashrc` file in the lines above, I get this error:
```
Error: The command exited with status 3
```
There's no further information about the error. If the error occurs in the `.bashrc` file, the EC2 instances just repeatedly die in an endless loop, presumably just as they're starting a session and sourcing `.bashrc`. Can you help me figure out what's going on here? Surely there must be a way to source a file on an agent? I have a sneaking suspicion it's related to switching user just because it's the only vaguely unusual thing I'm doing here, but surely it shouldn't be a problem going from `root` to a user with _less_ privileges? I'm also not sure how that would cause a problem with the `source`/`.` command, and only that command. I'm quite stumped. Thanks in advance!

**Comment by keithduncan** [comment] 2021-09-13 06:35
Hi @phazel, I have been unable to reproduce this issue in an agent 🤔 

I do note that the bootstrap script you have provided above _doesn’t_ run the curl pipeline as the buildkite-agent, the `su` command will run and exit and the subsequent command will run as the executing user. Could that be contributing to this issue?

I would suggest adding some more diagnostic commands to your pipeline before running the source to help diagnose it. Could you add the following to your step’s command:

```yaml
steps:
  - command:
      - "ls -la $$HOME/.nvm"
      - "cat $$HOME/.nvm/nvm.sh"
```

**Comment by keithduncan** [comment] 2021-09-26 23:57
I’m going to close this issue but please don’t hesitate to re-open it or leave a comment. You can also reach out to [Buildkite Support](https://buildkite.com/support) for more help.

**Closed by keithduncan** 2021-09-26 23:57 UTC
