### ISSUE TITLE
Boot time segfault on v3.36.0

### ISSUE THREAD

**Issue by KevinGreen** [buildkite/agent#1652] opened 2022-05-26 22:32 UTC
**Is your feature request related to a problem? Please describe.**
We just updated our agent to v3.36.0 from v3.35.0 and we're now seeing a segfault when our agent Docker container starts. We're using `buildkite/agent:3.36.0-ubuntu-20.04` as the base for our docker image.

The stack trace suggests it's while creating a logger but I don't know for sure. Our docker containers are logging to journald but from the application's point of view it should still be writing to stdout as usual.

**Describe the solution you'd like**
Shouldn't crash

**Describe alternatives you've considered**
We've downgraded back to v3.35.0 for now.

**Additional context**
Logs: ![image](https://user-images.githubusercontent.com/1634785/170589942-b5db3c93-19aa-41f6-a2d3-487383d52c8e.png)

**Comment by moskyb** [comment] 2022-05-26 22:40
oh man, this is embarrassing.... that nil pointer dereference is being caused by a [log statement that i accidentally left in the code](https://github.com/buildkite/agent/blob/main/clicommand/global.go#L130=) from https://github.com/buildkite/agent/pull/1635. I'll get a fix for this out ASAP.

In the meantime, would you mind sending through a redacted copy of your agent config? this isn't happening to me locally, and i'd be interested to see what the cause of it is.

**Closed** 2022-05-26 23:07 UTC
