### ISSUE TITLE
BUILDKITE_GIT_CLEAN_FLAGS is ignored

### ISSUE THREAD

**Issue by gtirloni** [buildkite/agent#756] opened 2018-05-04 13:21 UTC
**Issue**:

BUILDKITE_GIT_CLEAN_FLAGS environment variable defined in pipeline.yml is set correctly but it's ignored by agent.

Setting the variable in the agent configuration achieves the desired behavior but it applies to all jobs and we only want this pipeline to have this behavior. Additionally, hiding the pipeline-specific configuration in the agent configuration means the code repository doesn't have all the configuration needed to run CI and it must be kept somewhere else.

We cannot have buildkite-agent deleting all files between jobs because they are dependent on each other. The "Build" step will start a virtual machine and that needs to keep existing for the other steps.

**Agent**:
buildkite-agent v3.1.1

**Pipeline**:
```yaml
env:
  BUILDKITE_GIT_CLEAN_FLAGS: "-fqd"
steps:
  - name: "Build"
    command: "DISPLAY=:0 vagrant up --provider virtualbox"
    timeout_in_minutes: 20
  - wait

  - name: "Code Linter"
    command: "vagrant ssh -c 'cd /home/vagrant/sync/; $(npm bin)/grunt lint'"

  - name: "Browser Tests"
    command: "npm run test:vagrantBrowser"

  - name: "Node Tests"
    command: "npm run test:vagrantNode"

  - wait: ~
    continue_on_failure: true

  - name: "Cleanup"
    command: "vagrant destroy -f"
```

**Example build**:
https://buildkite.com/fluid-project/fluid-infusion/builds/227#97cb4e7a-8544-4cbd-899d-274123dbeec0

**Logs**:

```
Preparing working directory | 1s
  | $ cd /home/buildkite-agent-1/builds/h-0005-tor1-inclusivedesign-ca-1/fluid-project/fluid-infusion
  | $ git remote set-url origin https://github.com/fluid-project/infusion.git
  | $ git clean -fxdq
....
# Cleaning again to catch any post-checkout changes
  | $ git clean -fxdq
```

**Comment by gdolle** [comment] 2018-06-01 11:53
I confirm I've the same problem

**Comment by lox** [comment] 2018-06-28 13:40
Apologies for the slow response. This is actually by design (although poorly document), we don't allow `git-clean-flags` to be updated dynamically via env. You could however use the https://github.com/buildkite-plugins/git-clean-buildkite-plugin plugin to do this.

> We cannot have buildkite-agent deleting all files between jobs because they are dependent on each other. The "Build" step will start a virtual machine and that needs to keep existing for the other steps.

That is a tricky setup to get right, our steps are designed to be independent to allow parallel execution across lots of agents. Perhaps you could store the `machineid` of the vagrant VM created in [buildkite meta-data](https://buildkite.com/docs/builds/build-meta-data) so that you could ensure you were referencing the correct VM in subsequent steps?

**Comment by lox** [comment] 2018-10-08 07:15
I'm going to close this one for now, feel free to reply if we've missed something and we will re-open!

**Closed by lox** 2018-10-08 07:15 UTC
