### ISSUE TITLE
Plugin download fails due to GitHub connection timeout, implement retry?

### ISSUE THREAD

**Issue by philwo** [buildkite/agent#1248] opened 2020-07-17 11:02 UTC
Hi,

we have this [long standing issue](https://github.com/bazelbuild/continuous-integration/issues/964) on our Bazel CI where the Buildkite Agent occasionally fails to download the Docker plugin, because GitHub has a connection timeout. The agent doesn't retry in this case, but just immediately fails the job.

I think the agent already has retry logic for Git clone for the workspace preparation step - maybe we could reuse this when cloning plugins, too?

Happy to craft a PR for this.

**Comment by eleanorakh** [comment] 2020-07-28 23:49
Hi @philwo!

Yea, that sounds like a good approach. Very happy for you to craft up a PR for it 👍🏼

🙂

**Comment by keithduncan** [comment] 2021-08-13 01:44
Hi @philwo this looks like a duplicate of #1198, I’m going to close this and track plug-in fetch retries there, thanks!

**Closed by keithduncan** 2021-08-13 01:44 UTC
Labels: duplicate
