### ISSUE TITLE
Incorrect exit code 0

### ISSUE THREAD

**Issue by worxli** [buildkite/agent#1037] opened 2019-06-24 11:49 UTC
Agent: v3.13.0 on Ubuntu.

I think the following step should fail:
```
- label: "Test command "
  commands:
    - "false && echo \"echo false\""
    - "echo \"hello\""
```
But it exits with status 0.

Both
```
- label: "Test command "
  commands:
    - "false"
    - "echo \"hello\""
```
and
```
- label: "Test command "
  commands:
    - "false && echo \"echo false\""
```
correctly exit with 1.

**Comment by lox** [comment] 2019-06-24 11:54
Hi @worxli, if you run your agent with `--debug` it should show you what shell is being used to invoke the commands, it sounds like it might not be the default of `/bin/bash -e -c`?

**Comment by lox** [comment] 2019-06-24 11:56
Hmmm, actually I think I can repeat the issue.

**Comment by lox** [comment] 2019-06-24 11:58
```
> $ /bin/bash -e -c "false && echo \"echo false\"\necho \"hello\""
hello
```

Very strange. 🤔

**Comment by lox** [comment] 2019-06-24 12:01
I'll investigate and get a fix out @worxli! Thanks for the report.

**Comment by kormat** [comment] 2019-06-24 14:00
The simplest reproduction i can find is:
```
$ bash -e -c "false && :; echo end"
end
```

**Comment by kormat** [comment] 2019-06-24 14:25
Ok, i see what the problem is now. `set -e` is more subtle than i realised:

It only cares about the return value of "simple statements" (i.e. statements that don't contain `&&` or `||`), or the _last part_ of a `&&`/`||` chain.

See https://stackoverflow.com/questions/25794905/why-does-set-e-true-false-true-not-exit for more context.

In this case, `false && :` - the last part (`:`) is never evaluated, so `set -e` ignores the line.

IOW, this isn't buildkite's fault :)

What could be improved, though, is changing one of the examples given in the docs:
```
steps:
  - commands:
    - "npm install && npm test"
    - "moretests.sh"
    - "build.sh"
```
(which is something we had looked at to make sure what we were doing was valid)

**Comment by lox** [comment] 2019-06-28 06:58
You're right @kormat, it does look like that is how bash works 🤷🏼‍♂️ Very confusing! I'm not sure there is much we can do about it.

I'm going to close this one, as I reckon it's down to shell behaviour. Feel free to disagree if you have any suggestions!

**Closed by lox** 2019-06-28 06:58 UTC
