### ISSUE TITLE
Agent jobs hanging after process has finished

### ISSUE THREAD

**Issue by avsm** [buildkite/agent#775] opened 2018-05-24 15:03 UTC
Agent version: tried master branch as of today, and v3.1.2

I have a step that is building and pushing a docker container to the Hub.  It works fine 99% of the time, but one particular combination is triggering a hang that is causing the job to remain marked as running (and never terminating) after the process spawned has gone.  I see this when running the agent in debug mode on this particular job:

```
2018-05-24 15:07:00 DEBUG  [LineScanner] Error from scanner: bufio.Scanner: token too long
2018-05-24 15:07:00 DEBUG  [LineScanner] Waiting for callbacks to finish
2018-05-24 15:07:00 DEBUG  [LineScanner] Finished
```

and then when ctrl-C the agent, a clean stop fails:

```
^C2018-05-24 15:58:13 DEBUG  Received signal `INT`
2018-05-24 15:58:13 INFO   Forcefully stopping running jobs and stopping the agent
2018-05-24 15:58:13 INFO   Forcefully stopping agent. The current job will be canceled before disconnecting...
2018-05-24 15:58:13 INFO   Canceling job c68a303f-01ad-439f-8310-3c2ab3265779
2018-05-24 15:58:13 DEBUG  [Process] Sending signal: terminated to PID: 45791
2018-05-24 15:58:13 ERROR  [Process] Failed to send signal: terminated to PID: 45791 (*errors.errorString: os: process already finished)
2018-05-24 15:58:14 DEBUG  GET https://agent.buildkite.com/v3/jobs/c68a303f-01ad-439f-8310-3c2ab3265779
2018-05-24 15:58:14 DEBUG  _ GET https://agent.buildkite.com/v3/jobs/c68a303f-01ad-439f-8310-3c2ab3265779 (200 OK 93.440879ms)
```

ctrl-c again just leaves us in a loop of:

```
2018-05-24 16:02:23 INFO   Forcefully stopping running jobs and stopping the agent
2018-05-24 16:02:23 INFO   Forcefully stopping agent. The current job will be canceled before disconnecting...
2018-05-24 16:02:23 DEBUG  GET https://agent.buildkite.com/v3/jobs/c68a303f-01ad-439f-8310-3c2ab3265779
2018-05-24 16:02:24 DEBUG  _ GET https://agent.buildkite.com/v3/jobs/c68a303f-01ad-439f-8310-3c2ab3265779 (200 OK 99.930666ms)
```

A kill -9 works, but the job has to be manually cancelled from the web ui even though the agent has gone.

Mysteriously, this only happens on one job of thousands, and is on ppc64le if that is relevant (but other jobs complete just fine there)

**Comment by avsm** [comment] 2018-05-24 15:18
I'm mainly wondering what the best way to debug this next is. I've tried the master branch of the agent with the same issue, and it is reproducible in my environment.

**Comment by lox** [comment] 2018-05-25 00:45
Argh, I have a bad feeling that this is my doing with https://github.com/buildkite/agent/commit/1efed4015638f87fc9f8bfa7ac1ab11696a4aec1.

**Comment by lox** [comment] 2018-05-25 00:47
I believe what is happening is there is an error being thrown during scanning and then something about our signal handling is broken so that you get in a loop of being unable to `ctrl-c`. There are two bugs here, the original error `Error from scanner: bufio.Scanner: token too long` and then the loop that happens when trying to cancel the agent.

**Comment by lox** [comment] 2018-05-25 00:47
I'm inclined to roll back that commit.

**Comment by lox** [comment] 2018-05-25 00:59
Actually... I don't think that #617 came in till after v3.1.2, which probably precludes it from being the cause.

**Comment by lox** [comment] 2018-05-25 01:01
I'm officially perplexed.

**Comment by lox** [comment] 2018-05-25 01:01
Can you confirm which version of agent that error came from @avsm?

**Comment by lox** [comment] 2018-05-25 02:10
Accidentally auto-closed this. I've released version 3.2.0 of the agent to the beta channel @avsm, if you were able to test it and see if you run into this issue, I'd certainly appreciate it! I'll be flying for a few days, but will try and keep an eye out.

**Comment by avsm** [comment] 2018-05-25 06:50
Hm, I think there were two separate hangs we were seeing which confused the issue a little. The first came from Docker Hub, and that happened with v3.1.2 and the second was this issue and happened with the master branch.

After re-running the jobs with v3.1.2 and a working Docker Hub, there are no more hangs. So I think this was due to #617 indeed, as it only happens with a post-3.1.2 agent.

Incidentally, I'm compiling a ppc64le binary by hand at the moment, and it's working great in our multiarch build cluster. Adding a cross-compiled version of that arch to the Debian packaging would be handy -- I can test that arch now in production :)

**Comment by lox** [comment] 2018-06-28 13:23
Sounds like this one is sorted now. Let me know if I've missed something @avsm

**Closed** 2018-06-28 13:23 UTC
