### ISSUE TITLE
Occasional checkout fails

### ISSUE THREAD

**Issue by coen-hyde** [buildkite/agent#235] opened 2016-01-30 00:20 UTC
We're experiencing a weird git checkout issue. This error has been increasing in frequency recently. Any idea what is going on here?

```
Preparing build folder  0.2s
$ mkdir -p "/var/lib/buildkite-agent/builds/{{git_checkout_path}}"
$ cd "/var/lib/buildkite-agent/builds/{{git_checkout_path}}"
$ git remote set-url origin "git@github.com:{{repo}}.git"
$ git clean -fdq
$ git submodule foreach --recursive git clean -fdq
$ git fetch origin "+refs/pull/1705/head:"
From github.com:{{repo}}
 * branch            refs/pull/1705/head -> FETCH_HEAD
$ git checkout -qf "d0de339b3879631a6d6cd661fa900749ab5201de"
fatal: reference is not a tree: d0de339b3879631a6d6cd661fa900749ab5201de
```

**Comment by keithpitt** [comment] 2016-02-01 00:39
Hrm... I've not seen this issue before. But I'm keen to figure out what's going on. We've got a _similar_ issue to this, but the error message is different, so they may be different. But perhaps they're due to the same root issue? https://github.com/buildkite/agent/issues/226

**Comment by coen-hyde** [comment] 2016-02-01 19:22
I've done some more investigation and it appears Buildkite is fetching the wrong branch. In this case it is attempting to fetch pull request 1705 `git fetch origin "+refs/pull/1705/head:"`. But 1705 was merged almost a month ago which is why the git reference does not exist in the tree.

**Comment by coen-hyde** [comment] 2016-02-01 19:59
I've done some more investigation and it looks like Buildkite it fetching the wrong branch. In the case I'm currently investigating `#1705` was merged almost a month ago and is unrelated to the pull request currently being built. Strangely every failed git checkout is fetching `#1705` regardless of which branch is actually being tested. As an example. Look up build `bf1e4c49-25df-42a7-b853-bcce3e504c0f` on your end.

See:
![screen shot 2016-02-01 at 11 56 52 am](https://cloud.githubusercontent.com/assets/123503/12729355/2a4dcc76-c8db-11e5-9cc5-307d051c983e.png)

**Comment by wpillar** [comment] 2016-02-24 14:53
We're getting this exact error a *lot* at the moment.

**Comment by coen-hyde** [comment] 2016-02-25 21:53
@wpillar we "fixed" the issue by commenting out this code block in /usr/share/buildkite-agent/bootstrap.sh and replaced it with `buildkite-run "git fetch -q"`. Thanks to @keithpitt for pointing us in the right direction.

```
  if [[ "$BUILDKITE_PULL_REQUEST" != "false" ]] && [[ "$BUILDKITE_PROJECT_PROVIDER" == *"github"* ]]; then
    buildkite-run "git fetch origin \"+refs/pull/$BUILDKITE_PULL_REQUEST/head:\""
  else
    # If the commit is HEAD, we can't do a commit-only fetch, we'll need to use
    # the branch instead.
    if [[ "$BUILDKITE_COMMIT" == "HEAD" ]]; then
      buildkite-run "git fetch -q origin $BUILDKITE_BRANCH 2> /dev/null || git fetch -q"
    else
      # First try to fetch the commit only (because it's usually much faster).
      # If that doesn't work, just resort back to a regular fetch.
      buildkite-run "git fetch -q origin $BUILDKITE_COMMIT 2> /dev/null || git fetch -q"
    fi

    if [[ "$BUILDKITE_TAG" == "" ]]; then
      # Default empty branch names
      : "${BUILDKITE_BRANCH:=master}"
      buildkite-run "git reset --hard origin/$BUILDKITE_BRANCH"
    fi
  fi
```

The problem is $BUILDKITE_PULL_REQUEST is the wrong pull request. Somehow it's getting the value of 1705, which is a completely unrelated to the build in progress. Are you getting 1705 or a different value?

**Comment by toolmantim** [comment] 2016-03-17 05:21
This should be fixed in the latest version of both stable and unstable agents, and a bug we had in the backend. Sorry for the hassle!

**Closed by toolmantim** 2016-03-17 05:21 UTC

**Comment by cactus** [comment] 2018-04-06 23:09
Seeing this again occasionally with `buildkite-agent-3.0.0-2319`. Was there a regression?

**Comment by toolmantim** [comment] 2018-04-07 00:03
@cactus the agent is working as expected, but it’s seems there an issue with GitHub at the moment.

It seems the `refs/pull/{id}/head` ref fails to update if you have branch merge protection turned on for your GH repo, and “dismiss stale pull requests” enabled. The ref can get stuck to the commit before the first review dismissal.

The workaround is to force push new commits to the PRs branch, or turn merge protection off.

With the help of someone who managed to reproduce it, we’ve recreated the bug here: 
https://github.com/buildkite/pull-request-ref-head-bug/pull/1

```
git clone https://github.com/buildkite/pull-request-ref-head-bug.git
cd pull-request-ref-head-bug
git fetch origin refs/pull/1/head
git rev-parse FETCH_HEAD
```

You can see the `rev-parse` returns `a6f10f96` instead of `6cd1079d`.

GitHub will keep us posted on a fix, and I’ll keep this ticket updated as well.

**Comment by cactus** [comment] 2018-04-07 00:04
Thanks for the quick response @toolmantim !
👍

**Comment by pda** [comment] 2018-04-17 01:52
FYI we're seeing this periodically (most recently this morning) on a repo with “Dismiss stale pull request approvals when new commits are pushed” ticked for master branch protection.

**Comment by lox** [comment] 2018-04-17 02:02
Would be helpful if you emailed GitHub and asked them about it, it's an open issue @pda that we are trying to get them moving on.

**Comment by pda** [comment] 2018-04-17 02:27
Done;

> Subject: Bug: refs/pull/{id}/head stale; resolves to earlier commit
> 
> When we push a commit to a Pull Request in `cultureamp/[redacted]`, our CI pipeline pulls `refs/pull/{id}/head` expecting to receive the new commit. Occasionally (multiple times per day) `refs/pull/{id}/head` resolves to the previous commit, rather than the one just pushed. This breaks the CI build. I've heard other GitHub customers are having the same problem.
> 
> It may be relevant that the repository has branch protection on master with “Dismiss stale pull request approvals when new commits are pushed” enabled.

**Comment by pda** [comment] 2018-04-17 03:29
From GitHub:
> You are right, we have received a few reports similar to this one, and I can confirm that our engineers are actively investigating this matter, and they understand that this can be quite disruptive to your work, so we are sorry about this.
> Unfortunately I'm not sure if I have any workaround for this at the moment, and while I can't give you an estimated time of a fix, we will surely update you as soon as we have progress to share.

**Comment by pda** [comment] 2018-04-19 01:56
Follow-up from GitHub:

> Just a quick update to let you know that we've deployed a fix for this issue.
> Would you mind testing this out on your end?
> Please do let us know if you are still seeing this problem.

**Comment by lox** [comment] 2018-04-19 02:04
Thanks @pda!

**Comment by jtthackery** [comment] 2018-12-04 22:12
Hi,

It looks like we're running into this issue on one of our branches (or at least getting an identical error).  Was this confirmed to be fixed?

Thanks!

**Comment by lox** [comment] 2018-12-04 23:06
This issue related to branch protection on master in Github @jtthackery, do you have that enabled? Might be worth sending is a failing build to support@buildkite.com and we’ll have a look!

**Comment by taschik** [comment] 2019-11-14 22:20
Since two days we experience exactly the same behavior in our build pipeline. I upgraded 2/3 buildservers to Buildkite agent 3.16 although one was already on 3.16 for a bit and never reported this issue. However, even this one started showing the following behavior. Any idea on how to fix that?
```
$ git remote set-url origin git@github.com:xxx/repo.git
--
  | $ git clean -ffxdq
  | # Fetch and checkout pull request head from GitHub
  | $ git fetch -v --prune origin refs/pull/1393/head
  | From github.com:xxx/repo
  | * branch              refs/pull/1393/head -> FETCH_HEAD
  | # FETCH_HEAD is now `1a4c5b74c1185ebbdf12ea9d6f684263f2547737`
  | $ git checkout -f 07efcf61158e62482c8e7dc5ceb9226b92abc4bb
  | fatal: reference is not a tree: 07efcf61158e62482c8e7dc5ceb9226b92abc4bb
  | ⚠️ Warning: Checkout failed! exit status 128 (Attempt 1/3 Retrying in 2s)
```

Sometimes the solution is just to retry a bunch of time it sometimes until it works again, but for an automated system, this is very frustrating and not a solution. Any recommendation?

**Comment by pda** [comment] 2019-11-20 03:09
Hey @taschik, is it possible that a force-push was done to the PR while this build was starting up? That could overwrite the commit which your build is attempting to check out. Other than that, I would guess a timing issue on GitHub's side (which is what we were seeing last year in this thread).

**Comment by taschik** [comment] 2019-11-20 03:21
no not really, the support was able to help by resetting some cache that caused some troubles in this case. We apparently ran into an edge case bug of the backend. 🙈 It's all solved now and running smooth for a few days.

**Comment by williamcodes** [comment] 2022-03-28 16:12
We're seeing this exact issue again with buildkite agent version v3.33.3. Was there a regression? Is GitHub having issues again? Perhaps the agent could throw an error message to explicitly state what is causing the failure and what should be done about it.
