### ISSUE TITLE
Non-PR-triggered checkout of GitHub pull request ref with specific commit fails

### ISSUE THREAD

**Issue by ticky** [buildkite/agent#782] opened 2018-06-08 02:31 UTC
If a build attempts to check out a GitHub Pull Request ref (i.e. `refs/pull/1234/head`) with a specific commit set (this is likely if attempting to trigger another pipeline with the same branch and commit as a build triggered from a Pull Request webhook) the checkout will fail:

Triggering step:
```yml
steps:
  - label: "Trigger Deployment"
    trigger: "some-other-pipeline"
    build:
      message: "Deploy build for Pull Request $BUILDKITE_PULL_REQUEST"
      commit: "$BUILDKITE_COMMIT"
      branch: "refs/pull/$BUILDKITE_PULL_REQUEST/head"
```

Triggered build checkout phase:
```shell
$ cd /var/lib/buildkite-agent/builds/[checkout-dir]
$ git remote set-url origin git@github.com:some/example.git
$ git clean -fxdq
$ git fetch -v origin [$BUILDKITE_COMMIT]
error: Server does not allow request for unadvertised object [$BUILDKITE_COMMIT]
 
$ git fetch -v --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*

From github.com:some/example
 
 = [up to date]        master     -> origin/master
 
$ git checkout -f [$BUILDKITE_COMMIT]
fatal: reference is not a tree: [$BUILDKITE_COMMIT]
```

Because the triggered build doesn’t inherit the pull request information (`BUILDKITE_PULL_REQUEST`) from the parent build, [the GitHub PR-specific logic](https://github.com/buildkite/agent/blob/a9645cdfe3698270cd3b69afca6ae054c53b8dfc/bootstrap/bootstrap.go#L733-L750) doesn’t get applied. The working case falls through to [the HEAD case](https://github.com/buildkite/agent/blob/a9645cdfe3698270cd3b69afca6ae054c53b8dfc/bootstrap/bootstrap.go#L752-L762), which fetches by branch and subsequently fails.

I suspect we’ll need some logic added to say if the commit isn’t HEAD and the branch starts with `refs/pull`, then it needs to fetch the branch by name first, because PR commits aren’t advertised objects.

**Comment by lox** [comment] 2018-06-28 13:22
@sj26 any thoughts on this one?

**Comment by sj26** [comment] 2018-06-29 02:05
Using `refs/pull/$BUILDKITE_PULL_REQUEST/head` manually will always fail, unless you use a custom refspec, because `refs/pull/*` is not a branch and must be fetched specially.

I you use the actual branch and a commit then it might also fail if that commit isn't reachable from an actual brach in the base repo (maybe it only exists in a fork).

I suspect the answer is to pass the pull request env to the triggered build.

@ticky do you have a specific build which exhibited this issue?

**Comment by sj26** [comment] 2018-06-29 02:10
Note that this bit of your log is irrelevant:

```
$ git fetch -v origin [$BUILDKITE_COMMIT]
error: Server does not allow request for unadvertised object [$BUILDKITE_COMMIT]
```

That's an attempted optimisation to pull the specific commit, which some github repos don't have enabled. It falls back to fetching all branches and tags instead, which worked:

```
$ git fetch -v --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*

From github.com:some/example
 
 = [up to date]        master     -> origin/master
```

and means you have all advertised tags and branches for the source repo. But if the PR is from a forked then the commit might not be included.

**Comment by ticky** [comment] 2018-06-29 18:47
@sj26 conversation 3168 in support is where this came from, and has links.

> Using refs/pull/$BUILDKITE_PULL_REQUEST/head manually will always fail, unless you use a custom refspec, because refs/pull/* is not a branch and must be fetched specially.

This isn’t actually correct; that ref _can_ be fetched just fine in the current agent logic if specified as a branch with a commit of `HEAD`. It’s that if a specific SHA is given, `refs/pull/…/head` is never actually fetched, which is the problem.

If a `refs/pull/…/head` is supplied as a branch alone the checkout will work because that _is_ an advertised object, even for third-party PRs, but if an SHA is also supplied (i.e. to ensure it doesn’t pull later changes) it fails in the way described above, because _only_ the head is an advertised object when dealing with third-party pull requests, even though the commits before it will exist if the head is fetched.

> I suspect the answer is to pass the pull request env to the triggered build.

That could work too, but we should probably also handle the explicit “here’s a reference, and here’s a commit” case explicitly so this kind of behaviour is handled.

**Comment by sj26** [comment] 2018-07-03 03:52
> that ref can be fetched just fine in the current agent logic if specified as a branch with a commit of HEAD

Ah, because we fetch `$BUILDKITE_BRANCH` and then checkout `FETCH_HEAD`? Yeah, interesting. I guess that's a side effect of implementation and optimisation, though, not a feature, imho.

So I think the way we handle tags is detect `refs/tags/*` from `$BUILDKITE_BRANCH` and use it populate `$BUILDKITE_TAG`. What if we detect `refs/pull/*/head` and populate `$BUILDKITE_PULL_REQUEST`, meaning it will trigger the pull request fetch code path?

**Comment by lox** [comment] 2018-07-03 07:01
> Because the triggered build doesn’t inherit the pull request information (BUILDKITE_PULL_REQUEST) from the parent build

Couldn't we solve it by solving this bit? This causes problems elsewhere.

**Comment by lox** [comment] 2018-07-03 10:49
That won't work! We ignore it, don't we? That's the root cause IMO, currently folks can't make a build be PR-associated themselves

**Comment by clarkdave** [comment] 2018-11-08 04:35
Hey folks -- count me as another user who'd really appreciate the `BUILDKITE_PULL_REQUEST` and friends being passed down to triggered builds.

As a workaround we're passing them without the `BUILDKITE_PREFIX` when we generate our pipeline (to trigger multiple pipelines on the same monorepo):

```rb
:build => {
  :branch => ENV['BUILDKITE_BRANCH'],
  :commit => ENV['BUILDKITE_COMMIT'],
  :message => ENV['BUILDKITE_MESSAGE'],
  :env => {
    # Buildkite doesn't pass through PR environment vars when it triggers
    # a build, so we'll pass them through like this instead
    :PULL_REQUEST => ENV['BUILDKITE_PULL_REQUEST'] || 'false',
    :PULL_REQUEST_BASE_BRANCH => ENV['BUILDKITE_PULL_REQUEST_BASE_BRANCH'].to_s,
    :PULL_REQUEST_REPO => ENV['BUILDKITE_PULL_REQUEST_REPO'].to_s,
  },
}
```

This works for us, but means we had to change a bunch of pipelines to look for the new var. If we could have them passed down automatically, that'd be awesome.

If we could somehow pass them on with the same `BUILDKITE_*` name, that would also work!

**Comment by lox** [comment] 2019-01-21 21:45
I'm going to close this one for now.

**Closed by lox** 2019-01-21 21:45 UTC
