### ISSUE TITLE
Feature Request: Use meta-data inside of if conditional

### ISSUE THREAD

**Issue by jack1902** [buildkite/agent#1373] opened 2021-02-03 11:00 UTC
## Background

It would be great if it was possible to only run a `step` within a pipeline based on an `if` condition that targets a `meta-data` key.

Link to currently availabel conditions: https://buildkite.com/docs/pipelines/conditionals

### Example

Below i use an example that sets a meta-data key within one `step` and the following `step` only runs if the meta-data key `useful` is set to `true` otherwise that step won't run (This is a contrived example, the commands themselves could be much more complex)

```yaml
steps:
  - label: "meta-data setting step"
    commands:
    - echo "wow"
    - buildkite-agent meta-data set useful true

  - wait

  - label: "only run if useful"
    if: "meta-data.useful == true"
    command: echo "I am useful!"
```

### Use Case

I would like to only run two steps like `block & terraform apply` if the previous `terraform plan` actually had a change (having a pipeline just `block` all the time when it didn't need to seems pointless and results in builds being `cancelled` because the `apply` wasn't needed and that makes the build RED

**Comment by jayco** [comment] 2021-02-04 04:46
Thanks for the feature request @jack1902 

We have a current feature request for this in the forum here https://forum.buildkite.community/t/meta-data-in-conditional-clause/1190 which includes a work around.

I am going to close this out and you can keep of track of its progress in the forum (duplicate of https://github.com/buildkite/agent/issues/1155)

**Closed by jayco** 2021-02-04 04:46 UTC
