### ISSUE TITLE
Graceful shutdown doesn't actually exit

### ISSUE THREAD

**Issue by stiak** [buildkite/agent#399] opened 2016-11-07 00:57 UTC
I'm attempting to use the INT signal to stop the agent gracefully.  Here's my log output:

```
Nov  7 00:17:20 ip-172-18-15-42 systemd[1]: Started Buildkite Agent.
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: _           _ _     _ _    _ _                                _
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: | |         (_) |   | | |  (_) |                              | |
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: | |__  _   _ _| | __| | | ___| |_ ___    __ _  __ _  ___ _ __ | |_
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: | '_ \| | | | | |/ _` | |/ / | __/ _ \  / _` |/ _` |/ _ \ '_ \| __|
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: | |_) | |_| | | | (_| |   <| | ||  __/ | (_| | (_| |  __/ | | | |_
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: |_.__/ \__,_|_|_|\__,_|_|\_\_|\__\___|  \__,_|\__, |\___|_| |_|\__|
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: __/ |
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: http://buildkite.com/agent                    |___/
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 NOTICE Starting buildkite-agent v2.2 with PID: 1757
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 NOTICE The agent source code can be found here: https://github.com/buildkite/agent
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 NOTICE For questions and support, email us at: hello@buildkite.com
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   Configuration loaded from: /etc/buildkite-agent/buildkite-agent.cfg
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   Registering agent with Buildkite...
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   Successfully registered agent "ip-172-18-15-42" with meta-data [role=development]
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   Connecting to Buildkite...
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   Agent successfully connected
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   You can press Ctrl-C to stop the agent
Nov  7 00:17:21 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:21 INFO   Waiting for work...
Nov  7 00:17:26 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:26 INFO   Assigned job 019f56da-37b2-46b7-8bdd-ed4fda246d43. Accepting...
Nov  7 00:17:26 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:26 INFO   Starting job 019f56da-37b2-46b7-8bdd-ed4fda246d43
Nov  7 00:17:26 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:26 INFO   Starting to run script: /usr/share/buildkite-agent/bootstrap.sh
Nov  7 00:17:26 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:17:26 INFO   [Process] Process is running with PID: 1764
Nov  7 00:21:27 ip-172-18-15-42 systemd[1]: Stopping Buildkite Agent...
Nov  7 00:21:27 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:21:27 INFO   Gracefully stopping agent. Waiting for current job to finish before disconnecting...
Nov  7 00:26:27 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:26:27 INFO   Process with PID: 1764 finished with Exit Status: 0
Nov  7 00:26:30 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:26:30 INFO   Finished job 019f56da-37b2-46b7-8bdd-ed4fda246d43
Nov  7 00:26:30 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:26:30 INFO   Assigned job 5e760cc2-aa8e-42ae-9f76-10af88ea2dd5. Accepting...
Nov  7 00:26:30 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:26:30 INFO   Starting job 5e760cc2-aa8e-42ae-9f76-10af88ea2dd5
Nov  7 00:26:30 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:26:30 INFO   Starting to run script: /usr/share/buildkite-agent/bootstrap.sh
Nov  7 00:26:30 ip-172-18-15-42 buildkite-agent[1757]: 2016-11-07 00:26:30 INFO   [Process] Process is running with PID: 2316
```

**Assigned job 5e760cc2-aa8e-42ae-9f76-10af88ea2dd5. Accepting...** probably shouldn't happen after **Gracefully stopping agent. Waiting for current job to finish before disconnecting...**

Eventually systemd times out and kills the agent.

**Comment by toolmantim** [comment] 2016-11-07 01:05
Thanks for the bug report, and sorry you're having this problem @stiak. What's the exact version of the Buildkite Agent?

**Comment by stiak** [comment] 2016-11-07 01:09
This agent is v2.2

**Comment by akjones** [comment] 2016-11-09 21:58
Looks like this issue is similar to #402, so could be fixed by #403.

**Comment by stiak** [comment] 2016-11-09 22:09
I've verified that the graceful stop works when there are no further jobs waiting to be picked up.

**Comment by keithpitt** [comment] 2016-11-10 07:16
Hey all! I've confirmed that #403 fixes the issue and have rolled it into the v2.3 release! https://github.com/buildkite/agent/releases/tag/v2.3

Thanks again @grosskur for catching that one! Would have been pretty gnarly to figure out!

**Closed by keithpitt** 2016-11-10 07:16 UTC

**Comment by keithpitt** [comment] 2016-11-11 01:02
I've also pushed out a new beta release https://github.com/buildkite/agent/releases/tag/v3.0-beta.14 with this included! 💃

**Comment by grosskur** [comment] 2016-11-11 19:15
Thanks for merging it and pushing out the new releases! 👍
