### ISSUE TITLE
[feature] post-exit hook

### ISSUE THREAD

**Issue by zimbatm** [buildkite/agent#1363] opened 2021-01-21 13:34 UTC
### Problem statement

When build machines run out of disk space, news builds start failing.

### Proposed solution

Add a hook that gets executed whenever a task exits, and before a new task can be scheduled. That hook should be disconnected from the previous build and not affect the task result, even it if fails.

With that in place, it will become possible to run cleanup tasks to free disk space. Check for the general health of the machine. Or even shutdown the agent so it won't accept new tasks.

**Comment by keithduncan** [comment] 2021-07-28 02:21
Thank you for filing this issue @zimbatm! I’m going to close this as a duplicate of #1111 for a single place to track inter-job health check hook which could run clean up tasks, feel free to follow along there 🎉

**Closed by keithduncan** 2021-07-28 02:21 UTC
Labels: enhancement, hook
