### ISSUE TITLE
pre-exit hook not running for cancelled builds

### ISSUE THREAD

**Issue by Regner** [buildkite/agent#562] opened 2017-10-10 21:29 UTC
Using buildkite agent `v3.0-beta.32`. When we cancel a build the `pre-exit` hook is not run. In the case of older agents it was.

**Comment by lox** [comment] 2017-10-10 21:35
By older do you mean 2.x? Or earlier betas of 3.x?

**Comment by Regner** [comment] 2017-10-10 21:54
My apologies, I should have been more clear on that. 3 beta 29 to be specific.

**Comment by Regner** [comment] 2017-10-10 21:59
I just went to pull the links for an example and it appears I may have been mistaken. This might not be a difference of agent versions and instead a difference of failed vs cancelled. I thought both builds I was looking at were canceled ones.

It appears what I actually meant to say in my ticket was that failed builds run the pre-exit hook while cancelled ones do not.

**Comment by lox** [comment] 2017-10-10 22:09
Yup, that’s what I would have expected. I’ve been meaning to implement pre-exit on cancel. The difficulty is that a hard kill signal gets sent after 10 seconds, but it’s still useful to have. Apologies for the confusion!

**Comment by lox** [comment] 2017-11-04 02:04
This turns out to be a duplicate of https://github.com/buildkite/agent/issues/119, from 2015 😓

I'm going to look at this issue soon.

**Closed by lox** 2017-11-04 02:04 UTC
Labels: enhancement
