### ISSUE TITLE
'command' option as a list seems to be transformed into invalid syntax on Windows

### ISSUE THREAD

**Issue by kamalaknn** [buildkite/agent#470] opened 2017-05-11 10:09 UTC
Using the command property in the pipeline config yml as a list

```
command: 
  - "where node"
  - "node -v"
```
throws "The syntax of the command is incorrect." on a windows agent

However
```
command: "where node"
```

and 

```
command:
  - "where node"
```

work.

**Comment by mfeckie** [comment] 2017-10-19 08:29
Any progress with this issue humans?

**Comment by mfeckie** [comment] 2017-10-19 10:11
I've been playing around with it and notice that this works too

```yml
  -label: DoStuff
    command: 'cd app && yarn install && cd ..'
```

It seems like there's potentially some issue with escaping / packaging things on Windows.

I did clone this repo onto a windows box and tried to run the tests, but they all seemed very unhappy so I gave up

**Comment by lox** [comment] 2017-11-04 00:54
Apologies, no progress yet. Currently working on getting our test suites for the latest betas passing on Windows and then will tackle this issue.

**Comment by quasor** [comment] 2018-01-10 09:24
Should we use 3.0 or will this be back ported?

**Comment by lox** [comment] 2018-01-10 20:11
We will fix this prior to the 3.0 stable release! Thanks for your patience 🙇🏼

**Comment by keithpitt** [comment] 2018-03-13 01:08
This is fixed in 3.0, which will be released in the next few weeks. Thanks again!

**Comment by lox** [comment] 2018-03-17 04:56
Could you provide an example pipeline that is failing?

**Comment by kamalaknn** [comment] 2018-03-17 09:21
This is a simplified version of my pipeline

```json
{
"steps": [{
    "label": ":package: :windows:",
    "command": [
        "npm i",
        "npm run package",
    ],
    "timeout": 60,
    "agents": ["os=windows"]
}]
}
```

**Comment by lox** [comment] 2018-03-19 04:27
I'm really struggling to reproduce this @kamalaknn. Using this pipeline: https://gist.github.com/lox/8a2ae019dc3405ef28de8d901e8399f6

I see this with the latest beta: 

![image](https://user-images.githubusercontent.com/15758/37577988-cfbcf89a-2b89-11e8-90e7-cbcb6268fad0.png)

It fails because I don't have npm installed, but the script that is generated is correct. Could I trouble you to run your agent with `--debug` enabled and then email me a link to the failing build at support@buildkite.com?

**Comment by lox** [comment] 2018-03-21 02:07
I'm going to close this one for now as we've been unable to reproduce it. @kamalaknn if you run into this again, could you drop us an email with the above details and we will help troubleshoot.

**Closed by lox** 2018-03-21 02:07 UTC
Labels: bug, windows

**Comment by kamalaknn** [comment] 2018-03-21 06:30
@lox Sure. I haven't been able to get back to this. Will get back to you with more details.

**Comment by harryi3t** [comment] 2019-11-20 10:35
@lox Facing the same issue

Buildkite Version: 3.10.3

pipeline steps
```
steps:
  - label: ':windows:'
    command:
      - "echo 1"
      - "echo 2"
    agents:
      os: "windows"
      queue: "build"
```
Failed with the error
![image](https://user-images.githubusercontent.com/5207331/69231653-73e82f00-0baf-11ea-8745-7be72e799b36.png)

If I remove the 2nd step, like this
```
steps:
  - label: ':windows:'
    command:
      - "echo 1"
    agents:
      os: "windows"
      queue: "build"
```
then it works fine, as was commented by the OP
